"""empty message

Revision ID: 197aa6549060
Revises: 4e38a1d65e75
Create Date: 2019-05-21 15:54:36.876806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197aa6549060'
down_revision = '4e38a1d65e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_cardio', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.drop_column('users', 'specialty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialty', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    op.drop_column('users', 'is_cardio')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
