"""empty message

Revision ID: 19c4b18cd911
Revises: 5ef7188ba1df
Create Date: 2019-05-26 19:46:22.004585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c4b18cd911'
down_revision = '5ef7188ba1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'slots_db', 'users', ['doctorID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slots_db', type_='foreignkey')
    # ### end Alembic commands ###
