"""empty message

Revision ID: 2bb45fb0cce7
Revises: 895901481eba
Create Date: 2019-05-22 14:08:58.500555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bb45fb0cce7'
down_revision = '895901481eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users_That_Day_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Su1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('M1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('T1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('W1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('Th1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('F1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('S1', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('number_users_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_usersSu', sa.Integer(), nullable=True),
    sa.Column('number_usersM', sa.Integer(), nullable=True),
    sa.Column('number_usersT', sa.Integer(), nullable=True),
    sa.Column('number_usersW', sa.Integer(), nullable=True),
    sa.Column('number_usersTh', sa.Integer(), nullable=True),
    sa.Column('number_usersF', sa.Integer(), nullable=True),
    sa.Column('number_usersS', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('initials', sa.Text(), nullable=True))
    op.drop_column('users', 'initial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('initial', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'initials')
    op.drop_table('number_users_db')
    op.drop_table('Users_That_Day_db')
    # ### end Alembic commands ###
