"""empty message

Revision ID: 3c32cdc1f76e
Revises: 19c4b18cd911
Create Date: 2019-05-27 16:35:59.595495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c32cdc1f76e'
down_revision = '19c4b18cd911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users_That_Day_db', sa.Column('F2', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('F3', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('M2', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('M3', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('S2', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('S3', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('Su2', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('Su3', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('T2', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('T3', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('Th2', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('Th3', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('W2', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('Users_That_Day_db', sa.Column('W3', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersF1', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersF2', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersF3', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersM1', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersM2', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersM3', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersS1', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersS2', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersS3', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersSu1', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersSu2', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersSu3', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersT1', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersT2', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersT3', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersTh1', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersTh2', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersTh3', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersW1', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersW2', sa.Integer(), nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersW3', sa.Integer(), nullable=True))
    op.drop_column('number_users_db', 'number_usersSu')
    op.drop_column('number_users_db', 'number_usersF')
    op.drop_column('number_users_db', 'number_usersS')
    op.drop_column('number_users_db', 'number_usersTh')
    op.drop_column('number_users_db', 'number_usersT')
    op.drop_column('number_users_db', 'number_usersW')
    op.drop_column('number_users_db', 'number_usersM')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('number_users_db', sa.Column('number_usersM', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersW', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersT', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersTh', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersS', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersF', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('number_users_db', sa.Column('number_usersSu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('number_users_db', 'number_usersW3')
    op.drop_column('number_users_db', 'number_usersW2')
    op.drop_column('number_users_db', 'number_usersW1')
    op.drop_column('number_users_db', 'number_usersTh3')
    op.drop_column('number_users_db', 'number_usersTh2')
    op.drop_column('number_users_db', 'number_usersTh1')
    op.drop_column('number_users_db', 'number_usersT3')
    op.drop_column('number_users_db', 'number_usersT2')
    op.drop_column('number_users_db', 'number_usersT1')
    op.drop_column('number_users_db', 'number_usersSu3')
    op.drop_column('number_users_db', 'number_usersSu2')
    op.drop_column('number_users_db', 'number_usersSu1')
    op.drop_column('number_users_db', 'number_usersS3')
    op.drop_column('number_users_db', 'number_usersS2')
    op.drop_column('number_users_db', 'number_usersS1')
    op.drop_column('number_users_db', 'number_usersM3')
    op.drop_column('number_users_db', 'number_usersM2')
    op.drop_column('number_users_db', 'number_usersM1')
    op.drop_column('number_users_db', 'number_usersF3')
    op.drop_column('number_users_db', 'number_usersF2')
    op.drop_column('number_users_db', 'number_usersF1')
    op.drop_column('Users_That_Day_db', 'W3')
    op.drop_column('Users_That_Day_db', 'W2')
    op.drop_column('Users_That_Day_db', 'Th3')
    op.drop_column('Users_That_Day_db', 'Th2')
    op.drop_column('Users_That_Day_db', 'T3')
    op.drop_column('Users_That_Day_db', 'T2')
    op.drop_column('Users_That_Day_db', 'Su3')
    op.drop_column('Users_That_Day_db', 'Su2')
    op.drop_column('Users_That_Day_db', 'S3')
    op.drop_column('Users_That_Day_db', 'S2')
    op.drop_column('Users_That_Day_db', 'M3')
    op.drop_column('Users_That_Day_db', 'M2')
    op.drop_column('Users_That_Day_db', 'F3')
    op.drop_column('Users_That_Day_db', 'F2')
    # ### end Alembic commands ###
