"""empty message

Revision ID: 5ef7188ba1df
Revises: 2bb45fb0cce7
Create Date: 2019-05-24 12:32:17.275374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef7188ba1df'
down_revision = '2bb45fb0cce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Days',
    sa.Column('id', sa.Date(), nullable=False),
    sa.Column('first_AM', sa.Integer(), nullable=True),
    sa.Column('first_PM', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('third', sa.Integer(), nullable=True),
    sa.Column('fourth', sa.Integer(), nullable=True),
    sa.Column('fith', sa.Integer(), nullable=True),
    sa.Column('sixth', sa.Integer(), nullable=True),
    sa.Column('seventh', sa.Integer(), nullable=True),
    sa.Column('PostCall', sa.Integer(), nullable=True),
    sa.Column('Is_Weekend', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daynumber', sa.Integer(), nullable=True),
    sa.Column('shiftnumber', sa.Integer(), nullable=True),
    sa.Column('doctorID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots_db')
    op.drop_table('Days')
    # ### end Alembic commands ###
